### ISSUE TITLE
Check ZFR assignment #5

### ISSUE THREAD

**Issue by elchi28** [elchi28/Hostel-Harmony#14]
## Links for review
* [iter0-ZFR](https://github.com/elchi28/Hostel-Harmony/wiki/iter0-ZFR)
* [Issues](https://github.com/elchi28/Hostel-Harmony/issues)
* [Project schedules - KANBAN](https://github.com/elchi28/Hostel-Harmony/projects/1)

**Comment by AlonSchwartz** [comment]
Done, please check our work @eranhd
