### ISSUE TITLE
Available caretakers implementation 

### ISSUE THREAD

**Issue by elchi28** [elchi28/Hostel-Harmony#32]
check who is available for specific time and date

**Comment by AlonSchwartz** [comment]
Every day there is 3 staff members that are assigned to be a possible caretaker.
Only ONE staff member can be a caretaker at each time - so in every moment, there is MAXIMUM ONE staff member THAT IS ON DUTY BUT NOT AT THE HOSTEL.

Only after this staff member is back to hostel - a new caretaker can be assigned to an event.

So when a caretaker1 is assigned to an event, the other two can't be assigned to be a caretaker in events until caretaker1's event is done.

@elchi28  is that according to Ben's demand?

**Comment by elchi28** [comment]
At the moment is at hold due to difficulty of being ready in deadline

**Comment by elchi28** [comment]
Closed, decided not to implement it
