### ISSUE TITLE
Create ZFR Wiki page

### ISSUE THREAD

**Issue by AlonSchwartz** [elchi28/Hostel-Harmony#5]
The page needs to include:
- [x] Table of contents
- [x] Iteration Goals
- [x] Team Roles
- [x] Task Management (link to kanban, Total Estimation, screenshots)
- [x] Documentation (Relevant docs. diagrams)
- [x] Meeting Summaries
- [x] Retrospective
- [x] Process, Methods & Tools
- [x] Next Iteration Planning (link to iter1)

page template: https://github.com/jce-il/project-template/wiki/iter0-zfr

**Comment by elchi28** [comment]
zfr done
